schema: cas.entity.v0.1
id: PYFUNC-extras.profiling.run.Environment.on_repo
kind: entity
type: py.function
name: on_repo
status: draft
created_at: '2026-02-21T17:44:17.350021+00:00'
created_by: extractor:py.v0.1
source:
  repo: repo://httpie
  root: /tmp/httpie
  revision: git:HEAD
  file: extras/profiling/run.py
anchors:
- type: symbol
  value: extras.profiling.run.Environment.on_repo
- type: fingerprint
  value: 85133ef1737ac56fd72f0b7d91236f66d6efd9f666a3357868317525d78f7ec1
  algo: sha256
claims: []
relations: []
namespace: extras.profiling.run.Environment
