schema: cas.entity.v0.1
id: PYFUNC-httpie.context.Environment.rich_error_console
kind: entity
type: py.function
name: rich_error_console
status: draft
created_at: '2026-02-21T15:04:15.443496+00:00'
created_by: extractor:py.v0.1
source:
  repo: repo://httpie
  root: /tmp/httpie
  revision: git:HEAD
  file: httpie/context.py
anchors:
- type: symbol
  value: httpie.context.Environment.rich_error_console
- type: fingerprint
  value: bad1dfb25a7d93395549b50b8224ff79fc82b4eb34f1142efa12e5c7a2602f11
  algo: sha256
claims: []
relations: []
namespace: httpie.context.Environment
